notifications:
  email: false

sudo: true

git:
  depth: 3
  
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
      - libfuse-dev
      - fuse-utils
      - ghostscript

before_install:
  util/travis-before_install.sh

matrix:
  include:
    - os: linux
      language: python
      python: 3.5

#    - os: osx
#      language: python
#      python: 3.5      

install: 
    - mkdir build
    - cd build
    - cmake ..
    - make
    - cd ..

script:
    - cd build
    - python3 ../tests/mount.py
    - python3 ../tests/usage.py